export const IMAGES = {
  //NEW ICONS
  ic_arrowBack: require('../assets/icons/ic_arrowBack.png'),
  ic_badge: require('../assets/icons/ic_badge.png'),
  ic_calendar: require('../assets/icons/ic_calendar.png'),
  ic_catRead: require('../assets/icons/ic_catRead.png'),
  ic_catSleep: require('../assets/icons/ic_catSleep.png'),
  ic_catSmile: require('../assets/icons/ic_catSmile.png'),
  ic_confetti: require('../assets/icons/ic_confetti.png'),
  ic_doubleProfile: require('../assets/icons/ic_doubleProfile.png'),
  ic_house: require('../assets/icons/ic_house.png'),
  ic_leaderboards: require('../assets/icons/ic_leaderboards.png'),
  ic_math: require('../assets/icons/ic_math.png'),
  ic_plus: require('../assets/icons/ic_plus.png'),
  ic_torotot: require('../assets/icons/ic_torotot.png'),
  ic_catStanding: require('../assets/icons/ic_catStanding.png'),
  ic_add: require('../assets/icons/ic_add.png'),
  ic_google: require('../assets/icons/ic_google.png'),
  ic_whiteDoubleProfile: require('../assets/icons/ic_whiteDoubleProfile.png'),
  ic_whiteMath: require('../assets/icons/ic_whiteMath.png'),
  ic_whiteGrades: require('../assets/icons/ic_whiteGrades.png'),
  ic_whiteLeaderboards: require('../assets/icons/ic_whiteLeaderboards.png'),
  ic_doubleprofile1: require('../assets/icons/ic_doubleprofile1.png'),
  ic_math1: require('../assets/icons/ic_math1.png'),
  ic_calendar1: require('../assets/icons/ic_calendar1.png'),
  ic_leaderboards1: require('../assets/icons/ic_leaderboards1.png'),
};
