export const ROUTES = {
  LANDING_SCREEN: 'LANDING_SCREEN',
  REGISTER_SCREEN: 'REGISTER_SCREEN',
  HOME_SCREEN: 'HOME_SCREEN',
  GRADES_SCREEN: 'GRADES_SCREEN',
  LEADERBOARDS_SCREEN: 'LEADERBOARDS_SCREEN',
  PEOPLE_SCREEN: 'PEOPLE_SCREEN',
  CREATE_TODO_SCREEN: 'CREATE_TODO_SCREEN',
  ADD_QUESTION_SCREEN: 'ADD_QUESTION_SCREEN',
};
